import type { Metadata } from "next";
import { Barlow, Barlow_Condensed, Bellefair } from "next/font/google";
import "./globals.css";

const BarlowFont = Barlow({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-barlow",
});

const BarlowCondensedFont = Barlow_Condensed({
  variable: "--font-barlow-condensed",
  subsets: ["latin"],
  weight: "400",
});

const BelleFairFont = Bellefair({
  subsets: ["latin"],
  variable: "--font-bellefair",
  weight: "400",
});

export const metadata: Metadata = {
  title: "Space Tourism | werdNa",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiase ${BarlowFont.variable} ${BarlowCondensedFont.variable} ${BelleFairFont.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
